# nireon_v4\domain\ports\idea_service_port.py
from typing import Protocol, runtime_checkable, Optional, Dict, Any # Add Optional, Dict, Any
from domain.ideas.idea import Idea
from domain.context import NireonExecutionContext
@runtime_checkable
class IdeaServicePort(Protocol):
    def save(self, idea: Idea) -> None:
        ...
    def get_by_id(self, idea_id: str) -> Idea:
        ...
    def create_idea(self, *, text: str, parent_id: str | None=None, context: NireonExecutionContext | None=None, metadata: Optional[Dict[str, Any]] = None, method: str = 'manual') -> Idea:
        ...
    def get_all_ideas(self) -> list[Idea]:
        ...
    def add_world_fact(self, *, idea_id: str, fact_id: str, context: NireonExecutionContext | None=None) -> bool:
        ...
    def get_children(self, idea_id: str) -> list[Idea]:
        ...