# nireon_v4/configs/default/mechanisms/explorer_primary.yaml
# These are default values that override Pydantic defaults if specified.
max_depth: 4
application_rate: 0.6
exploration_strategy: "depth_first"
# divergence_strength: 0.15 # if this field exists in ExplorerConfig