version: "1.0"
rules:
  - id: "route_high_trust_to_quantifier"
    description: "When a high-trust assessment is published, send it to the QuantifierAgent (a Processor)."
    namespace: "synthesis_loop"
    priority: 10
    enabled: false # This rule is currently disabled.
    conditions:
      - type: "signal_type_match"
        signal_type: "TrustAssessmentSignal"
      - type: "payload_expression"
        expression: "signal.trust_score > 6.0 and payload.is_stable == True"
    actions:
      - type: "trigger_component"
        component_id: "quantifier_agent_primary"
        input_data_mapping:
          idea_id: "payload.idea_id"
          idea_text: "payload.assessment_details.metadata.idea_text"
          assessment_details: "payload.assessment_details"
          
  - id: "high_trust_idea_amplification"
    description: "Amplify ideas with very high trust scores by feeding them to the Catalyst"
    namespace: "trust"
    priority: 100
    enabled: true
    conditions:
      - type: "signal_type_match"
        signal_type: "TrustAssessmentSignal"
      - type: "payload_expression"
        # FIX: Use direct attribute access and check for existence at each level.
        # This avoids the "Function not permitted" error.
        expression: "signal.trust_score > 8.0 and payload.axis_scores and payload.axis_scores.novel and payload.axis_scores.novel.score and payload.axis_scores.novel.score > 8.0"
    actions:
      - type: "trigger_component"
        component_id: "catalyst_instance_01"
        template_id: "AMPLIFY_HIGH_TRUST"
        input_data_mapping:
          target_idea_id: "payload.idea_id"
          objective: "payload.assessment_details.metadata.objective"