version: "1.0"
rules:
  - id: "route_analytical_seed_to_quantifier"
    description: "If a seed is tagged for analysis, bypass the Explorer and send it directly to an analyst agent for hypothesis generation."
    namespace: "analytical_processing"
    priority: 5 # Higher priority than the basic_explorer rule
    enabled: true
    conditions:
      - type: "signal_type_match"
        signal_type: "SeedSignal"
      - type: "payload_expression"
        # This checks if the 'tags' list in the metadata contains 'analysis_query'
        expression: "exists(payload.metadata.tags) and 'analysis_query' in payload.metadata.tags"
    actions:
      - type: "trigger_component"
        component_id: "quantifier_agent_primary"
        input_data_mapping:
          # The QuantifierAgent expects 'idea_text' and 'objective'
          idea_text: "payload.text"
          objective: "payload.metadata.objective"
          idea_id: "payload.seed_idea_id"