version: "1.0"
rules:
  - id: "catalyst_on_promising_ideas"
    description: "Trigger Catalyst on stable, high-potential ideas that aren't yet perfect, to explore adjacent possibilities."
    namespace: "synthesis"
    priority: 85
    enabled: true
    conditions:
      - type: "signal_type_match"
        signal_type: "TrustAssessmentSignal"
      - type: "payload_expression"
        expression: "signal.trust_score > 6.5 and signal.trust_score < 8.5 and payload.is_stable == True"
    actions:
      - type: "trigger_component"
        component_id: "catalyst_instance_01"
        input_data_mapping:
          target_idea_id: "payload.idea_id"
          objective: >-
            payload.assessment_details.metadata.objective if exists(payload.assessment_details.metadata.objective) 
            else 'Amplify and find novel variations of this concept.'