version: "1.0"
rules:
  - id: "update_idea_scores_on_assessment"
    description: "Update idea scores in database when trust assessment is made"
    namespace: "persistence"
    priority: 20 # Run after main assessment processing
    enabled: true
    conditions:
      - type: "signal_type_match"
        signal_type: "TrustAssessmentSignal"
    actions:
      - type: "trigger_component"
        component_id: "idea_score_updater"
        input_data_mapping:
          signal: "signal"