version: "1.0"
rules:
  - id: "route_math_query_to_principia"
    description: "When a structured MathQuerySignal is detected, trigger the primary Principia math agent."
    namespace: "math_processing"
    priority: 15 # Higher than default, but lower than core loops
    enabled: true
    conditions:
      - type: "signal_type_match"
        signal_type: "MathQuerySignal"
    actions:
      - type: "trigger_component"
        component_id: "principia_agent_primary"
        input_data_mapping:
          # --- These lines were already here ---
          expression: "expression"
          operations: "operations"
          natural_language_query: "natural_language_query"
          # --- ADD THIS LINE ---
          payload: "payload" 