version: "1.0"
rules:
  - id: "high_trust_idea_amplification"
    description: "Amplify ideas with high trust scores"
    namespace: "trust"
    priority: 10
    enabled: true
    conditions:
      - type: "signal_type_match"
        signal_type: "TrustAssessmentSignal"
      - type: "payload_expression"
        # FIX: Changed 'is not None' to '!= None' for better compatibility
        expression: "signal.trust_score != None and signal.novelty_score != None and signal.trust_score > 0.8 and signal.novelty_score > 0.6"
    actions:
      - type: "trigger_component"
        component_id: "catalyst_mechanism"
        template_id: "AMPLIFY_HIGH_TRUST"
        input_data_mapping:
          idea_content: "payload.idea_content"
          trust_level: "signal.trust_score"

  - id: "low_trust_quarantine"
    description: "Quarantine ideas with very low trust scores"
    namespace: "trust"
    priority: 5
    enabled: true
    conditions:
      - type: "signal_type_match"
        signal_type: "TrustAssessmentSignal"
      - type: "payload_expression"
        # FIX: Changed 'is not None' to '!= None' for better compatibility
        expression: "signal.trust_score != None and signal.trust_score < 0.2"
    actions:
      - type: "emit_signal"
        signal_type: "IdeaQuarantinedSignal"
        payload:
          idea_id: "{{ signal.payload.idea_id }}"
          reason: "Low trust score"
          trust_score: "{{ signal.trust_score }}"