# nireon/configs/default/global_app_config.yaml
env: "production" # Can be 'production', 'staging', 'test', 'default'

bootstrap_strict_mode: true

# Default feature flags
feature_flags:
  enable_schema_validation: true 
  enable_self_certification: true
  enable_rbac_bootstrap: true    
  enable_concurrent_initialization: false # Keep false for easier debugging initially
  enable_component_tracing: false # Typically for dev


bootstrap_max_init_loops: 10 # From V3 reference, good to make configurable

# FrameFactoryService configuration
frame_factory_config:
  root_frame_name: "NIREON_EXPLORER_TEST_ROOT"
  log_frame_operations: true
  max_frames: 100 # Keep low for testing
  enable_frame_expiration: false # Simpler for now
  cleanup_interval_seconds: 600

reactor:
  rules_path: "configs/reactor/rules" # Makes the path explicit
  max_recursion_depth: 10

llm:
  parameters:
    defaults: {}

mechanism_gateway_config: {} # No specific gateway config needed for this test

