# nireon_v4/configs/default/global_app_config.yaml
env: "default" # Default environment name

bootstrap_strict_mode: true # Default strictness for bootstrap

# Default feature flags (V4ConfigLoader currently adds some if missing)
feature_flags:
  enable_schema_validation: true # More strict by default
  enable_self_certification: true
  enable_rbac_bootstrap: false # False by default, can be overridden by env or manifest
  enable_component_tracing: false # Typically for dev
  # Add other V4 specific feature flags here as they become relevant

# Bootstrap operational parameters
bootstrap_max_init_loops: 10 # From V3 reference, good to make configurable

# Placeholder for other global settings as needed
# system_log_level: "INFO"