version: "1.0"
metadata:
  name: "NIREON V4 Generic Configuration"
  description: "Production-ready configuration with generic, provider-agnostic naming"
  author: "NIREON Team"
  created_at: "2025-06-05T10:00:00Z"
  updated_at: "2025-06-05T12:00:00Z"

shared_services:
  EventBusPort:
    enabled: true
    class: "infrastructure.event_bus.memory_event_bus.MemoryEventBus"
    config:
      max_history: 1000
      enable_persistence: false

  LLMPort:
    enabled: true
    class: "infrastructure.llm.router:LLMRouter"
    config:
      config_file: "configs/default/llm_config.yaml"

  EmbeddingPort:
    enabled: true
    class: "infrastructure.embeddings.embeddings.EmbeddingAdapter"
    config:
      provider: "sentence_transformers"
      model: "all-MiniLM-L6-v2"
      dimensions: 384
      cache_size: 1000
      timeout: 30
    config_override:
      api_key: "${EMBEDDING_API_KEY}"
      base_url: "${EMBEDDING_API_URL:-https://api.example.com/v1}"

  IdeaRepositoryPort:
    enabled: true
    class: "infrastructure.persistence.idea_repository.IdeaRepository"
    config:
      provider: "sqlite"
      db_path: "runtime/ideas.db"
      enable_wal_mode: true
      timeout: 30.0
    config_override:
      connection_string: "${DATABASE_URL:-postgresql://localhost/nireon}"
      pool_size: 5

  FeatureFlagsManager:
    enabled: true
    class: "infrastructure.feature_flags.FeatureFlagsManager"
    config:
      default_flags:
        enable_exploration: true
        enable_catalyst: true
        enable_schema_validation: true

  IdeaService:
    enabled: true
    class: "application.services.idea_service.IdeaService"
    config: {}

mechanisms:
  explorer_primary:
    enabled: true
    class: "components.mechanisms.explorer.service.ExplorerMechanism"
    metadata_definition: "components.mechanisms.explorer.service.EXPLORER_METADATA"
    config:
      max_depth: 4
      application_rate: 0.6
      exploration_strategy: "depth_first"
      max_variations_per_level: 3
      enable_semantic_exploration: true
      enable_llm_enhancement: true
      creativity_factor: 0.7
      exploration_timeout_seconds: 45.0
    epistemic_tags:
      - "generator"
      - "mutator"
      - "explorer"

observers: {}

managers: {}

composites: {}

orchestration_commands: {}

environment_overrides:
  development:
    shared_services:
      LLMPort:
        class: "bootstrap.bootstrap_helper.placeholders.PlaceholderLLMPortImpl"
      EmbeddingPort:
        class: "bootstrap.bootstrap_helper.placeholders.PlaceholderEmbeddingPortImpl"
  testing:
    shared_services:
      IdeaRepositoryPort:
        class: "bootstrap.bootstrap_helper.placeholders.PlaceholderIdeaRepositoryImpl"
      EventBusPort:
        class: "bootstrap.bootstrap_helper.placeholders.PlaceholderEventBusImpl"
  production:
    shared_services: {}
